### ISSUE TITLE
Migration error on Redmine 4.1.1

### ISSUE THREAD

**Issue by markusneg** [westaco/westaco_versions#1]
We use this plugin successfully with Redmine 4.0 and now also with 4.1.1, however, upon migrating (rake redmine:plugins) I receive an error (see above). Nonetheless the plugin still seems to work as expected. As a workaround for migrating other plugins I temporarily remove the plugin folder.

```
I, [2021-03-31T07:18:51.401595 #200]  INFO -- : Migrating to PopulateVersionsDates (3)
== 3 PopulateVersionsDates: migrating =========================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "versions" of relation "versions" does not exist
LINE 1: UPDATE "versions" SET versions.start_date = (SELECT MIN(issu...
                              ^
: UPDATE "versions" SET versions.start_date = (SELECT MIN(issues.start_date) FROM issues WHERE issues.fixed_version_id = versions.id) WHERE "versions"."start_date" IS NULL
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `async_exec_params'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `block (2 levels) in exec_no_cache'
/usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:610:in `block in exec_no_cache'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:94:in `exec_delete'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:170:in `update'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `update'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/relation.rb:337:in `update_all'
/usr/src/redmine/plugins/westaco_versions/db/migrate/003_populate_versions_dates.rb:7:in `up'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:777:in `up'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:817:in `exec_migration'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:797:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:796:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1343:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `migrate'
/usr/src/redmine/lib/redmine/plugin.rb:510:in `up'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/usr/src/redmine/lib/redmine/plugin.rb:542:in `migrate_plugin'
/usr/src/redmine/lib/redmine/plugin.rb:483:in `migrate'
/usr/src/redmine/lib/redmine/plugin.rb:497:in `block in migrate'
/usr/src/redmine/lib/redmine/plugin.rb:496:in `each'
/usr/src/redmine/lib/redmine/plugin.rb:496:in `migrate'
/usr/src/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/src/redmine/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "versions" of relation "versions" does not exist
LINE 1: UPDATE "versions" SET versions.start_date = (SELECT MIN(issu...

```

**Comment by prody1605** [comment]
solved

**Comment by prody1605** [comment]
solved
