### ISSUE TITLE
Plugin not compatible with REDMINE v5.1.3

### ISSUE THREAD

**Issue by subnauez** [westaco/westaco_versions#4]
Hello,

I'm currently upgrading a REDMINE instance to v5.1.3 with westaco_versions plugin.
Unfortunately, I'm facing REDMINE issues when I activate westaco_versions plugin that shoud be compatible with REDMINE 5.1.x

With the westaco_versions plugin 0.0.5 :

> redmine01# rake redmine:plugins:migrate RAILS_ENV=production
> rake aborted!
> LoadError: cannot load such file -- /opt/redmine/plugins/westaco_versions/lib/westaco_versions_controller_patch.rb (LoadError)
> <internal:/usr/local/lib/ruby/site_ruby/3.2/rubygems/core_ext/kernel_require.rb>:37:in `require'
> <internal:/usr/local/lib/ruby/site_ruby/3.2/rubygems/core_ext/kernel_require.rb>:37:in `require'
> /opt/redmine/plugins/westaco_versions/init.rb:6:in `<top (required)>'
> /opt/redmine/lib/redmine/plugin_loader.rb:31:in `load'
> /opt/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
> /opt/redmine/lib/redmine/plugin_loader.rb:108:in `each'
> /opt/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
> /opt/redmine/config/environment.rb:16:in `<top (required)>'
> <internal:/usr/local/lib/ruby/site_ruby/3.2/rubygems/core_ext/kernel_require.rb>:37:in `require'
> <internal:/usr/local/lib/ruby/site_ruby/3.2/rubygems/core_ext/kernel_require.rb>:37:in `require'
> Tasks: TOP => redmine:plugins:migrate => environment
> (See full trace by running task with --trace)

With the westaco_versions plugin 0.0.4, I can migrate the plugin without issue but there is a internal server error while running REDMINE :

> I, [2024-09-19T09:35:01.525061 #51886]  INFO -- : [b382ba0b-8ca7-432a-9b93-2081c51ba04d] Completed 500 Internal Server Error in 11ms (ActiveRecord: 1.8ms | Allocations: 5551)
> F, [2024-09-19T09:35:01.526026 #51886] FATAL -- : [b382ba0b-8ca7-432a-9b93-2081c51ba04d]
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d] ActionView::Template::Error (undefined method `exists?' for File:Class):
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d]     13: <%= javascript_heads %>
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d]     14: <%= heads_for_theme %>
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d]     15: <%= heads_for_auto_complete(@project) %>
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d]     16: <%= call_hook :view_layouts_base_html_head %>
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d]     17: 
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d]     18: <%= yield :header_tags -%>
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d]     19: </head>
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d]
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d] plugins/westaco_versions/lib/westaco_versions_hook.rb:5:in `view_layouts_base_html_head'
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d] lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d] lib/redmine/hook.rb:66:in `each'
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d] lib/redmine/hook.rb:66:in `block in call_hook'
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d] lib/redmine/hook.rb:63:in `call_hook'
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d] lib/redmine/hook.rb:101:in `call_hook'
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d] app/views/layouts/base.html.erb:16
> [b382ba0b-8ca7-432a-9b93-2081c51ba04d] lib/redmine/sudo_mode.rb:61:in `sudo_mode'

Do you know what's going wrong ?

I'd appreciate your help resolving this issue and stay at your disposal if you need further information.

Best regards.

**Comment by subnauez** [comment]
@prody1605 : Any news about this issue ?

**Comment by UserVladimir37** [comment]
I ran into the same problem when migrating from reminder 4.1.1 to 5.1.3

**Comment by UserVladimir37** [comment]
there is no file in the repository "westaco_versions/lib/westaco_versions_controller_patch.rb"

**Comment by subnauez** [comment]
Any chance to see this issue solved ?
